const ips = [
  {
    ip_address: '61.216.161.147',
    country: 'Taiwan',
    country_code: 'TW',
    continent: 'Asia',
    continent_code: 'AS',
    city: 'Taichung',
    county: 'Taichung City',
    region: 'Taiwan',
    region_code: '04',
    timezone: 'Asia/Taipei',
    owner: null,
    longitude: 120.6839,
    latitude: 24.1469,
    currency: 'TWD',
    languages: ['zh-TW', 'zh', 'nan', 'hak'],
  },
  {
    ip_address: '124.160.153.248',
    country: 'China',
    country_code: 'CN',
    continent: 'Asia',
    continent_code: 'AS',
    city: 'Ningbo',
    county: null,
    region: 'Zhejiang',
    region_code: '02',
    timezone: 'Asia/Shanghai',
    owner: null,
    longitude: 121.5495,
    latitude: 29.8782,
    currency: 'CNY',
    languages: ['zh-CN', 'yue', 'wuu', 'dta', 'ug', 'za'],
  },
];

export default ips;
